/*
 * This source file was generated by the Gradle 'init' task
 */
package volungemv2;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.stage.Stage;
import java.net.URL;

public class App extends Application {
    @Override
    public void start(Stage stage) throws Exception {
        URL fxmlUrl = getClass().getResource("/fxml/Login.fxml");
        if (fxmlUrl == null) {
            System.err.println("FXML file not found at: /fxml/Login.fxml");
            System.err.println("Please check if the file exists in src/main/resources/fxml/");
            return;
        }
        
        Parent root = FXMLLoader.load(fxmlUrl);
        Scene scene = new Scene(root);
        stage.getIcons().add(new Image(getClass().getResourceAsStream("/img/LogoVolungem.png")));
        stage.setTitle("VolunGem");
        stage.setScene(scene);
        stage.show(); // Tambahkan ini untuk menampilkan window
    }

    public static void main(String[] args) {
        launch(args);
    }

    public String getGreeting() {
        return "Hello, VolunGem!";
    }
}